-- ================================================
--  DATABASE: DEMO (QUẢN LÝ GIAO HÀNG)
--  Tác giả: Nguyễn Phúc
--  Mô tả: Tạo đầy đủ bảng + ràng buộc + cascade + kiểm tra logic
-- ================================================

-- Nếu database chưa có, có thể tạo:
-- CREATE DATABASE demo;
-- USE demo;

-- =======================
-- BẢNG KHÁCH HÀNG
-- =======================
CREATE TABLE KHACHHANG (
    MAKHACHHANG VARCHAR(9) PRIMARY KEY NOT NULL,
    TENCONGTY NVARCHAR(100) NOT NULL,
    TENGIAODICH NVARCHAR(100) NULL,
    DIACHI NVARCHAR(200) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NULL,
    DIENTHOAI VARCHAR(15) NULL,
    FAX VARCHAR(15) NULL
);

-- =======================
-- BẢNG NHÀ CUNG CẤP
-- =======================
CREATE TABLE NHACUNGCAP (
    MACONGTY VARCHAR(9) PRIMARY KEY NOT NULL,
    TENCONGTY NVARCHAR(100) NOT NULL,
    TENGIAODICH NVARCHAR(100) NULL,
    DIACHI NVARCHAR(200) NULL,
    DIENTHOAI VARCHAR(15) NULL,
    FAX VARCHAR(15) NULL,
    EMAIL VARCHAR(100) UNIQUE NULL
);

-- =======================
-- BẢNG LOẠI HÀNG
-- =======================
CREATE TABLE LOAIHANG (
    MALOAIHANG VARCHAR(9) PRIMARY KEY,
    TENLOAIHANG NVARCHAR(100) NOT NULL
);

-- =======================
-- BẢNG MẶT HÀNG
-- =======================
CREATE TABLE MATHANG (
    MAHANG VARCHAR(9) PRIMARY KEY,
    TENHANG NVARCHAR(100) NOT NULL,
    MACONGTY VARCHAR(9) NOT NULL,
    MALOAIHANG VARCHAR(9) NOT NULL,
    SOLUONG INT NOT NULL CHECK (SOLUONG >= 0),
    DONVITINH NVARCHAR(20) NOT NULL,
    GIAHANG DECIMAL(18,2) NOT NULL DEFAULT 0,
    CONSTRAINT FK_MATHANG_NHACUNGCAP FOREIGN KEY (MACONGTY)
        REFERENCES NHACUNGCAP(MACONGTY)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_MATHANG_LOAIHANG FOREIGN KEY (MALOAIHANG)
        REFERENCES LOAIHANG(MALOAIHANG)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- =======================
-- BẢNG NHÂN VIÊN
-- =======================
CREATE TABLE NHANVIEN (
    MANHANVIEN VARCHAR(9) PRIMARY KEY,
    HO NVARCHAR(50) NOT NULL,
    TEN NVARCHAR(50) NOT NULL,
    NGAYSINH DATE NULL,
    NGAYLAMVIEC DATE NOT NULL,
    DIACHI NVARCHAR(200) NULL,
    DIENTHOAI VARCHAR(15) NULL,
    LUONGCOBAN DECIMAL(18,2) NOT NULL DEFAULT 0,
    PHUCAP DECIMAL(18,2) NOT NULL,
    CONSTRAINT CK_TUOI_NHANVIEN CHECK (
        DATEDIFF(YEAR, NGAYSINH, GETDATE()) BETWEEN 18 AND 60
    )
);

-- =======================
-- BẢNG ĐƠN ĐẶT HÀNG
-- =======================
CREATE TABLE DONDATHANG (
    SOHOADON VARCHAR(9) PRIMARY KEY,
    MAKHACHHANG VARCHAR(9) NOT NULL,
    MANHANVIEN VARCHAR(9) NOT NULL,
    NGAYDATHANG DATE NOT NULL,
    NGAYGIAOHANG DATE NULL,
    NGAYCHUYENHANG DATE NULL,
    NOIGIAOHANG NVARCHAR(200) NULL,
    CONSTRAINT FK_DONDATHANG_KHACHHANG FOREIGN KEY (MAKHACHHANG)
        REFERENCES KHACHHANG(MAKHACHHANG)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_DONDATHANG_NHANVIEN FOREIGN KEY (MANHANVIEN)
        REFERENCES NHANVIEN(MANHANVIEN)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CK_NGAYGIAO_CHUYEN CHECK (
        (NGAYGIAOHANG IS NULL OR NGAYGIAOHANG >= NGAYDATHANG)
        AND (NGAYCHUYENHANG IS NULL OR NGAYCHUYENHANG >= NGAYDATHANG)
    )
);

-- =======================
-- BẢNG CHI TIẾT ĐẶT HÀNG
-- =======================
CREATE TABLE CHITIETDATHANG (
    SOHOADON VARCHAR(9) NOT NULL,
    MAHANG VARCHAR(9) NOT NULL,
    GIABAN DECIMAL(18,2) NOT NULL,
    SOLUONG INT NOT NULL DEFAULT 1,
    MUCGIAMGIA DECIMAL(5,2) NULL DEFAULT 0
        CHECK (MUCGIAMGIA BETWEEN 0 AND 100),
    PRIMARY KEY (SOHOADON, MAHANG),
    CONSTRAINT FK_CHITIETDATHANG_SOHOADON FOREIGN KEY (SOHOADON)
        REFERENCES DONDATHANG(SOHOADON)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_CHITIETDATHANG_MAHANG FOREIGN KEY (MAHANG)
        REFERENCES MATHANG(MAHANG)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- ================================================
-- ✅ HOÀN THÀNH
-- Tất cả các bảng đã có: 
--  + Giá trị mặc định cho SOLUONG & MUCGIAMGIA
--  + Ràng buộc ngày giao / ngày chuyển
--  + Ràng buộc tuổi nhân viên 18–60
--  + Cascade delete/update đầy đủ
-- ================================================
